### ISSUE TITLE
Gateway: update keycloak auth

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit-Extensions/quantum-serverless#1088]
### Steps to reproduce the problem

https://github.com/Qiskit-Extensions/quantum-serverless/pull/954

Keycloak is no longer a provider in django allauth https://github.com/pennersr/django-allauth/blob/fdd5c3bdf0ebc2b471d491f9d06f01eb541bce68/docs/socialaccount/providers/keycloak.rst#L2

### What is the current behavior?

```
Traceback (most recent call last):
  File "/home/runner/work/quantum-serverless/quantum-serverless/gateway/.tox/lint/lib/python3.9/site-packages/pylint_django/checkers/foreign_key_strings.py", line 114, in open
    django.setup()
  File "/home/runner/work/quantum-serverless/quantum-serverless/gateway/.tox/lint/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/runner/work/quantum-serverless/quantum-serverless/gateway/.tox/lint/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/runner/work/quantum-serverless/quantum-serverless/gateway/.tox/lint/lib/python3.9/site-packages/django/apps/config.py", line 193, in create
    import_module(entry)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'allauth.socialaccount.providers.keycloak'
```

### What is the expected behavior?

We decided to sunset Keycloak from our project:

- [ ] Create a custom authentication process for a debug user
- [ ] Remove (default) JWT authentication from gateway and update tests and docs that they must be using it
- [ ] Remove Keycloak from the project

**Comment by Tansito** [comment]
Trying to update keycloak's helm package I discovered an interesting conflict:
- Docker version 21 is not compatible with our current configuration
- Same for dj-rest & django-allauth packages

I will try to solve this for next week. Maybe I will need your help @akihikokuroda , @IceKhan13 .

**Comment by Tansito** [comment]
After internal discussion between @akihikokuroda , @IceKhan13 , @psschwei and I, we decided to take the next steps:

- Drop support for Keycloak
- Implement a mock to support some kind of authentication for tests and local development without the need to use IQP Token
- Improve our current support for OpenID protocol (low priority task)

**Comment by IceKhan13** [comment]
xref: https://github.com/Qiskit-Extensions/quantum-serverless/issues/1131

**Comment by IceKhan13** [comment]
Keycloak dropped in #1131 and https://github.com/Qiskit-Extensions/quantum-serverless/pull/1134
